import 'package:finland/models/place.dart';

class PlacesHelper {
  static Place getPlace(String id) =>
      places.firstWhere((element) => element.id == id);

  static List<Place> places = [
    Place(
      id: '0',
      asset: 'assets/png/places/image1.png',
      name: 'Moomin Museum in Tampere',
      rating: '315 ratings',
      category: Category.withTheKids,
      content: [
        "Location: Tampere",
        "Description: The Moomin Museum in Tampere is a delightful attraction dedicated to the beloved Moomin characters created by Finnish author Tove Jansson. The museum features a wide range of Moomin-themed exhibitions and interactive displays, making it an engaging and educational experience for children of all ages. Kids can explore the magical world of the Moomins, meet the whimsical characters, and learn more about the stories that have captivated readers for generations.",
        "Interactive Activities: The museum often hosts workshops, storytelling sessions, and creative activities that allow children to engage with the Moomin stories in a hands-on way. From arts and crafts to interactive storytelling, there are plenty of opportunities for kids to immerse themselves in the enchanting Moomin universe.",
        "Souvenir Shop: The museum's gift shop offers a wide selection of Moomin-related merchandise, including books, toys, and other memorabilia, so children can take home a piece of the Moomin magic.",
        "Cafeteria: The museum's cafeteria serves a variety of Moomin-themed snacks and treats, making it a fun place for a snack or lunch break.",
        "Visiting the Moomin Museum is not only entertaining but also a great way for kids to discover and appreciate Finnish literature and creativity. It's an ideal destination for families looking for a whimsical and educational experience in Finland.",
      ],
    ),
    Place(
      id: '1',
      asset: 'assets/png/places/image2.png',
      name: 'Ranua Wildlife Park in Ranua',
      rating: '1512 ratings',
      category: Category.withTheKids,
      content: [
        "Location: Ranua, Northern Finland",
        "Description: Ranua Wildlife Park is a unique and family-friendly attraction located in the heart of Finnish Lapland. It's the northernmost zoo in the world and offers visitors the chance to get up close to the diverse wildlife found in the Arctic region. Kids will be enthralled by the opportunity to see various northern animals in spacious, natural-like enclosures.",
        "Arctic Animal Encounters: The park is home to a wide range of Arctic animals, including polar bears, reindeer, lynx, wolves, and many bird species. Families can observe these animals in a setting that closely resembles their natural habitats.",
        "Educational Programs: Ranua Wildlife Park offers educational programs and guided tours that provide insight into the lives and behaviors of the animals. It's a fantastic opportunity for kids to learn about the Arctic ecosystem and conservation efforts.",
        "Winter Activities: If you visit in winter, you can enjoy special activities like husky sledding, snowshoeing, and even the chance to meet Santa Claus.",
        "Cafes and Souvenir Shops: The park has on-site cafes and souvenir shops where you can purchase snacks, drinks, and mementos to remember your visit.",
        "Ranua Wildlife Park is an ideal destination for families who want to introduce their children to the wonders of Arctic wildlife. It's both an educational and entertaining experience, and the opportunity to witness these remarkable animals up close is something kids are sure to remember. Be prepared for changing weather conditions, especially if you visit in winter, and dress warmly to fully enjoy the experience.",
      ],
    ),
    Place(
      id: '2',
      asset: 'assets/png/places/image3.png',
      name: 'Serena Water Park in Espoo',
      rating: '7346 ratings',
      category: Category.withTheKids,
      content: [
        "Location: Espoo, Greater Helsinki",
        "Description: Serena Water Park is one of the largest indoor water parks in Scandinavia, making it an ideal destination for families looking to have a blast in any season. With a wide range of water slides, pools, and attractions, it's a perfect spot for kids of all ages to enjoy water-based adventures.",
        "Water Slides and Pools: Serena offers a variety of thrilling water slides, including both indoor and outdoor options. The most famous is the Mega Water Slide, one of the longest indoor water slides in Europe. There are also heated pools and relaxing areas for those who prefer a more tranquil experience.",
        "Children's Play Areas: Younger children have their own designated play areas, complete with smaller slides, shallow pools, and water toys. This ensures that even the littlest ones can join in the fun.",
        "Saunas and Spa: Serena also features saunas and spa areas where adults can unwind while kids continue enjoying the water park.",
        "Food and Refreshments: Several eateries are available within the park, offering a variety of snacks, meals, and refreshments.",
        "Serena Water Park provides endless entertainment for kids and a chance for families to have a fun and active day out, no matter the weather. Whether you're seeking thrilling water slides or a more relaxed water experience, Serena has something for everyone. Be sure to check the water park's operating hours and any specific rules or height restrictions for certain rides.",
      ],
    ),
    Place(
      id: '3',
      asset: 'assets/png/places/image4.png',
      name: 'Linnanmäki Amusement Park in Helsinki',
      rating: '2361 ratings',
      category: Category.withTheKids,
      content: [
        "Location: Helsinki",
        "Description: Linnanmäki is one of Finland's oldest and most beloved amusement parks, offering a fantastic day of family fun. Located in the heart of Helsinki, this park has something for everyone, from thrilling rides to entertaining shows and games.",
        'Rides and Attractions: Linnanmäki boasts a variety of rides, including roller coasters, carousels, and other attractions suitable for different age groups. Popular rides include the wooden roller coaster "Vuoristorata" and the adrenaline-pumping "Hurjakuru."',
        "Children's Rides: For younger kids, the park offers a separate area with gentler rides and attractions designed with their safety and enjoyment in mind.",
        "Entertainment: Linnanmäki regularly hosts entertaining shows, such as magic performances, acrobatics, and puppet theater, ensuring there's always something happening on the stage.",
        "Carnival Games: Kids can enjoy carnival games, try their luck at winning prizes, and have a great time with games like ring-toss and duck fishing.",
        "Food and Snacks: The park features a variety of food stalls, cafes, and restaurants serving everything from cotton candy to traditional Finnish dishes.",
        "Linnanmäki is a fantastic place for families to create cherished memories while enjoying thrilling rides and delightful entertainment. Check the park's website for details on opening hours, ticket prices, and any seasonal events or special offers.",
      ],
    ),
    Place(
      id: '4',
      asset: 'assets/png/places/image5.png',
      name: 'Kotka Maretarium in Kotka',
      rating: '542 ratings',
      category: Category.withTheKids,
      content: [
        "Location: Kotka, Southern Finland",
        "Description: The Kotka Maretarium is an excellent family attraction dedicated to showcasing the diverse marine life of the Baltic Sea and the Gulf of Finland. It provides a fascinating and educational experience for children and adults alike.",
        "Aquarium Exhibits: The Maretarium features a variety of aquariums, each representing a different aquatic habitat. Visitors can observe and learn about the marine creatures native to the region, including fish, crustaceans, and other sea life.",
        "Touch Pools: Kids will love the interactive touch pools, where they can get up close and personal with some of the marine life, such as starfish and crabs. It's a hands-on opportunity for children to learn about these creatures.",
        "Educational Programs: The Maretarium offers educational programs, guided tours, and workshops that cater to children's curiosity and provide insights into marine biology and conservation.",
        "Café and Gift Shop: The facility includes a café for snacks and refreshments, and a gift shop where you can find marine-themed souvenirs.",
        "Outdoor Area: The Maretarium is located along the beautiful Kotka waterfront, providing a scenic view of the Gulf of Finland. You can enjoy a leisurely stroll by the sea and take in the fresh sea air.",
        "The Kotka Maretarium offers an engaging and interactive experience for kids, fostering an appreciation for the marine world and its conservation. It's a great stop for families interested in aquatic life and the Baltic Sea ecosystem. Be sure to check the Maretarium's schedule for guided tours and workshops to make the most of your visit.",
      ],
    ),
    Place(
      id: '5',
      asset: 'assets/png/places/image6.png',
      name: 'Lahden Tivoli in Lahti',
      rating: '2156 ratings',
      category: Category.withTheKids,
      content: [
        "Location: Lahti, Southern Finland",
        "Description: Lahden Tivoli is a family-friendly amusement park that offers a wide range of fun attractions and activities for children of all ages. Located in the heart of Lahti, it's a perfect destination for a day of excitement and entertainment.",
        "Amusement Rides: The park features a variety of amusement rides, including classic carousels, ferris wheels, and bumper cars. These rides are suitable for children and families, providing thrills and excitement.",
        "Kiddie Rides: For the youngest visitors, there are gentle kiddie rides designed with their safety and enjoyment in mind. These rides are perfect for toddlers and preschoolers.",
        "Games and Carnival Fun: Lahden Tivoli offers a wide selection of carnival games and attractions, including games of skill and chance. Kids can try their hand at winning prizes or enjoy the lively atmosphere.",
        "Snacks and Treats: You'll find a range of food stalls and kiosks throughout the park, serving classic amusement park snacks like cotton candy, popcorn, and ice cream.",
        "Events and Entertainment: The park often hosts special events and live entertainment, including performances, magic shows, and more, adding an extra layer of excitement to the visit.",
        "Lahden Tivoli is a great place for families to create lasting memories, enjoy thrilling rides, and indulge in classic amusement park treats. It's an excellent option for a day of family fun in Lahti. Make sure to check the park's schedule for special events or live entertainment happening during your visit.",
      ],
    ),
    Place(
      id: '6',
      asset: 'assets/png/places/image7.png',
      name: 'Angry Birds Activity Park in Vuokatti',
      rating: '3413 ratings',
      category: Category.withTheKids,
      content: [
        "Location: Vuokatti, Kainuu region",
        "Description: The Angry Birds Activity Park is a themed indoor entertainment center based on the popular mobile game Angry Birds. It's an exciting destination for families, especially if your children are fans of the game.",
        "Interactive Play Areas: The park offers a range of interactive play areas, including climbing structures, slides, and obstacle courses, all with an Angry Birds twist. Kids can engage in physical activities while having fun.",
        "Angry Birds Characters: Visitors can meet life-sized Angry Birds characters and take photos with them, adding a touch of magic to the experience.",
        "Mini Golf: The park also has a mini-golf course with Angry Birds-themed holes, providing a fun and competitive activity for the whole family.",
        "Cafeteria: The on-site cafeteria offers a variety of snacks and refreshments, allowing for a break between activities.",
        "Merchandise Shop: You'll find an Angry Birds merchandise shop where kids can pick up toys, clothing, and other souvenirs related to the popular game.",
        "The Angry Birds Activity Park is a fantastic destination for families, offering a combination of physical play, themed entertainment, and the opportunity to meet beloved characters. It's especially suited for younger children who enjoy active and imaginative play. Be sure to check the park's hours and any special events they may be hosting during your visit.",
      ],
    ),
    Place(
      id: '7',
      asset: 'assets/png/places/image8.png',
      name: 'Heureka Science Centre in Vantaa',
      rating: '833 ratings',
      category: Category.withTheKids,
      isPremium: true,
      content: [
        "Location: Vantaa, Greater Helsinki",
        "Description: Heureka is a hands-on science center that offers a wide range of interactive and educational experiences for kids and families. It's a place where children can learn about various scientific phenomena in a fun and engaging way.",
        "Interactive Exhibits: Heureka features numerous interactive exhibits covering topics such as physics, astronomy, biology, and technology. Kids can participate in experiments, explore hands-on displays, and discover the wonders of science.",
        "Planetarium and Dome Theatre: The planetarium and dome theatre at Heureka offer captivating shows about space, the Earth, and the natural world. It's a great opportunity for kids to embark on a virtual journey through the cosmos.",
        "Workshops and Demonstrations: The science center regularly hosts workshops, demonstrations, and live experiments that provide a deeper understanding of scientific principles. These activities are both entertaining and educational.",
        "Educational Programs: Heureka offers educational programs for school groups and families, making it a valuable resource for learning about various scientific topics.",
        "Cafeteria and Gift Shop: The on-site cafeteria provides a place to grab a meal or snack. The gift shop offers science-related souvenirs, books, and educational toys.",
        "Heureka Science Centre is an ideal place for curious kids and families to explore the world of science in a hands-on and entertaining way. It fosters an appreciation for learning and discovery in a fun and interactive environment. Check the center's website for information about current exhibits, shows, and special events.",
      ],
    ),
    Place(
      id: '8',
      asset: 'assets/png/places/image9.png',
      name: 'Linnanmäki Amusement Park in Helsinki',
      rating: '723 ratings',
      category: Category.withTheKids,
      isPremium: true,
      content: [
        "Location: Helsinki",
        "Description: Linnanmäki is one of Finland's premier amusement parks and a popular family-friendly attraction in the capital city, Helsinki. It offers a wide range of rides, games, and entertainment for visitors of all ages.",
        'Amusement Rides: Linnanmäki is home to an array of amusement rides, including thrilling roller coasters, water rides, and more family-oriented attractions. Some of the park\'s iconic rides include the wooden roller coaster "Vuoristorata" and the twisting "Kirnu."',
        "Children's Rides: For the littlest visitors, there are gentler rides and attractions specifically designed for young children. These rides provide a safe and enjoyable experience for toddlers and preschoolers.",
        "Carnival Games: The park features numerous carnival games and skill-based attractions, where kids can test their abilities and try to win prizes. Games like ring-toss and duck fishing offer a touch of classic carnival fun.",
        "Live Entertainment: Linnanmäki often hosts live entertainment, such as magic shows, musical performances, and circus acts, which add an extra layer of excitement to your visit.",
        "Dining Options: Various eateries, snack bars, and restaurants are available within the park, serving a range of food and refreshments to keep everyone fueled for a full day of fun.",
        "Linnanmäki Amusement Park is a fantastic place for families to spend an exciting day together. Whether you're looking for heart-pounding thrills or gentler rides for the little ones, Linnanmäki has something for everyone. Be sure to check the park's schedule for live shows and special events happening during your visit.",
      ],
    ),
    Place(
      id: '9',
      asset: 'assets/png/places/image10.png',
      name: 'Heureka Science Centre in Vantaa',
      rating: '6594 ratings',
      category: Category.withTheKids,
      isPremium: true,
      content: [
        "Location: Vantaa, Greater Helsinki",
        "Description: Heureka Science Centre is an interactive and educational attraction that provides an engaging experience for families, with a focus on science and exploration. It's a place where kids can learn while having fun.",
        "Interactive Exhibits: Heureka offers a wide range of hands-on and interactive exhibits covering various scientific fields, including physics, biology, astronomy, and technology. Children can engage in experiments, manipulate displays, and explore the marvels of science.",
        "Planetarium and Dome Theatre: The center features a planetarium and dome theatre that present captivating shows about space, the Earth, and the natural world. These immersive experiences allow kids to embark on exciting virtual journeys through the cosmos.",
        "Workshops and Demonstrations: Heureka regularly hosts workshops, demonstrations, and live experiments that provide in-depth insights into scientific principles. These activities are both entertaining and educational, making learning a fun experience.",
        "Educational Programs: Heureka offers educational programs tailored to different age groups, including school groups and families. These programs enhance the understanding of various scientific topics.",
        "Cafeteria and Gift Shop: The center has an on-site cafeteria for grabbing a meal or snack, as well as a gift shop where you can find science-related souvenirs, books, and educational toys.",
        "Heureka Science Centre is an ideal place for families to ignite curiosity, explore scientific concepts, and appreciate the wonders of the natural world. It encourages a love for learning in an interactive and entertaining setting. Be sure to check the center's website for information about current exhibits, shows, and special events.",
      ],
    ),
    Place(
      id: '10',
      asset: 'assets/png/places/image11.png',
      name: 'Santa Claus Village in Rovaniemi',
      rating: '2361 ratings',
      category: Category.romantic,
      content: [
        "Location: Rovaniemi, Lapland",
        "Description: Santa Claus Village is an enchanting and iconic destination for lovers, situated in the heart of Lapland. It offers a unique romantic experience that revolves around the magic of Christmas and the Arctic Circle.",
        "Crossing the Arctic Circle: Visit the Arctic Circle line that runs through the village, where you and your partner can cross the line hand in hand and receive a special Arctic Circle Crossing Certificate.",
        "Meeting Santa Claus: Embrace the spirit of Christmas by meeting Santa Claus himself. Share your wishes and dreams together in the cozy setting of Santa's office.",
        "Aurora Borealis Tours: Lapland is renowned for its Northern Lights displays. Consider booking an Aurora Borealis tour to witness the breathtaking natural light show, which is a truly romantic and awe-inspiring experience.",
        "Snowy Adventures: Engage in various winter activities such as husky sledding, snowmobiling, or taking a reindeer sleigh ride through the snowy landscapes. These adventures provide the perfect backdrop for romantic moments.",
        "Cozy Accommodations: Lapland offers a range of cozy accommodations, including glass igloos and wilderness cabins, where you and your partner can enjoy a night under the starry Arctic sky.",
        "Santa Claus Village is a magical place for couples to experience the charm of the North, the spirit of Christmas, and the beauty of the Arctic environment. Whether you're crossing the Arctic Circle or witnessing the Northern Lights, you'll create unforgettable memories together. Be sure to book accommodations well in advance, especially during peak holiday seasons.",
      ],
    ),
    Place(
      id: '11',
      asset: 'assets/png/places/image12.png',
      name: 'Suomenlinna - Helsinki',
      rating: '7346 ratings',
      category: Category.romantic,
      content: [
        "Location: Helsinki",
        "Description: Suomenlinna is a historic sea fortress located on a group of islands in the Helsinki archipelago. This UNESCO World Heritage Site provides a serene and romantic setting for couples to explore and enjoy each other's company.",
        "Historic Fortifications: Explore the well-preserved fortifications, tunnels, and bastions of Suomenlinna. The historic ambience adds a unique touch to your romantic getaway, and you can learn about the fortress's rich history together.",
        "Scenic Walks: The islands are connected by scenic pathways and bridges, making it an ideal place for a leisurely stroll hand in hand. The lush parks and coastal views create a picturesque backdrop.",
        "Picnic Spots: Suomenlinna offers plenty of picturesque spots for a romantic picnic. Bring some Finnish delicacies and enjoy a meal with your partner in the charming island setting.",
        "Art and Culture: Visit the art galleries and museums on the islands to appreciate the local art and culture. These venues often feature temporary exhibitions that can spark meaningful discussions.",
        "Sea Views: The shoreline of Suomenlinna offers breathtaking sea views and a tranquil atmosphere. Enjoy the serene waters of the Baltic Sea and relish quiet moments together.",
        "Cafés and Restaurants: The islands have lovely cafés and restaurants where you can savor Finnish cuisine or simply enjoy a cup of coffee with your loved one.",
        "Suomenlinna is a fantastic destination for couples seeking a peaceful and historical setting for their romantic getaway. The blend of nature, history, and culture creates a unique atmosphere that invites you to connect on a deeper level. Be sure to check the ferry schedule from Helsinki to Suomenlinna for a smooth visit.",
      ],
    ),
    Place(
      id: '12',
      asset: 'assets/png/places/image13.png',
      name: 'Northern Lights in Lapland',
      rating: '315 ratings',
      category: Category.romantic,
      content: [
        "Location: Various locations in Lapland, such as Rovaniemi, Levi, and Inari.",
        "Description: Lapland, in the northern reaches of Finland, offers an incredible opportunity for a romantic rendezvous under the mesmerizing Northern Lights, also known as the Aurora Borealis. This natural wonder is one of the most captivating and romantic experiences you can share with your partner.",
        'Aurora Hunting: Lapland is known for its pristine wilderness, which provides an excellent backdrop for viewing the Northern Lights. Consider booking an "Aurora Hunting" tour with a local guide who can take you to the best viewing spots and share their expertise about this natural phenomenon.',
        "Cozy Accommodations: Lapland offers a range of unique and cozy accommodations, including glass igloos and snow hotels, where you can spend the night gazing at the night sky from the warmth of your room. This intimate setting is perfect for cuddling up and enjoying the celestial show.",
        "Photography Opportunities: If you're both photography enthusiasts, the Northern Lights offer a magical opportunity for capturing stunning photos together. Share the excitement of capturing the dancing lights on your camera.",
        "Warm Saunas and Hot Tubs: After a night of Northern Lights viewing, warm up in a traditional Finnish sauna or relax in a hot tub under the starry sky. This is a perfect way to end your romantic evening.",
        "Sami Culture: Explore the indigenous Sami culture of Lapland. You can visit a traditional Sami reindeer farm or join cultural experiences such as dog sledding or snowshoeing with Sami guides.",
        "Local Cuisine: Savor Finnish and Sami cuisine at local restaurants. Lapland is known for its delectable Arctic dishes like reindeer and Arctic char, which can be enjoyed in a cozy and romantic dining setting.",
        "Experiencing the Northern Lights together in Lapland is an incredibly romantic and awe-inspiring adventure. The breathtaking natural light show and the serenity of the Arctic wilderness provide a perfect backdrop for couples to create unforgettable memories. Be sure to plan your trip during the winter months, as this is the prime time for Northern Lights viewing in Lapland.",
      ],
    ),
    Place(
      id: '13',
      asset: 'assets/png/places/image14.png',
      name: 'Merenkallio (Merenkallio) - Turku Archipelago',
      rating: '723 ratings',
      category: Category.romantic,
      content: [
        "Location: Turku Archipelago",
        "Description: Merenkallio is a picturesque destination situated within the Turku Archipelago, a vast network of islands along the southwestern coast of Finland. It offers an ideal romantic escape with its serene natural beauty and intimate island settings.",
        "Private Island Retreats: Many private island cottages and cabins are available for rent in the Turku Archipelago. Merenkallio is known for its tranquil island accommodations, offering couples the opportunity to enjoy their own private retreat amidst the archipelago's stunning landscapes.",
        "Secluded Beaches: The Turku Archipelago boasts numerous secluded beaches, where you and your partner can enjoy a leisurely stroll, relax on the shore, or even take a refreshing swim in the crystal-clear waters. These beaches provide the perfect setting for a romantic picnic or a moment of peaceful contemplation.",
        "Boating and Sailing: The archipelago offers fantastic opportunities for boating and sailing adventures. Rent a small boat, kayak, or even a sailing yacht to explore the archipelago together. The calm waters and beautiful scenery create a romantic backdrop for your nautical escapade.",
        "Sunsets and Stargazing: Merenkallio and the Turku Archipelago, in general, are renowned for their breathtaking sunsets and pristine night skies. Watch the sun dip below the horizon, and then marvel at the stars as you enjoy a quiet evening with your loved one.",
        "Local Seafood Cuisine: Savor delicious local seafood dishes at cozy restaurants scattered throughout the archipelago. Enjoy fresh catches of fish, crayfish, and other delectable seafood in a romantic dining setting.",
        "Sauna Experiences: The Finnish sauna culture is deeply ingrained in the archipelago, and many accommodations include private saunas. Share a sauna session with your partner and then cool off with a dip in the sea for a truly authentic and romantic Finnish experience.",
        "Merenkallio and the Turku Archipelago offer a serene and intimate setting for couples seeking a romantic escape. The combination of secluded island accommodations, natural beauty, and outdoor activities creates an unforgettable romantic experience. Be sure to book your island retreat or accommodations well in advance, especially during the summer months when the archipelago is at its most popular.",
      ],
    ),
    Place(
      id: '14',
      asset: 'assets/png/places/image15.png',
      name: 'Gavo Shali - Karelia',
      rating: '833 ratings',
      category: Category.romantic,
      content: [
        "Location: Karelia, Eastern Finland",
        "Description: Gavo Shali is a charming and romantic guesthouse situated in the pristine wilderness of Karelia, Eastern Finland. It offers an idyllic and secluded setting for couples to connect with nature and each other.",
        "Cozy Log Cabins: The guesthouse provides cozy log cabins with all the modern amenities, ensuring a comfortable and romantic stay. These cabins are nestled in the midst of the Karelian forests, offering privacy and a warm, rustic atmosphere.",
        "Sauna by the Lake: Enjoy traditional Finnish sauna sessions together in a private lakeside sauna cabin. After the sauna, you can take a refreshing dip in the clear waters of the lake or simply relax on the pier, surrounded by the peaceful nature of Karelia.",
        "Hiking and Nature Walks: The surrounding area is perfect for romantic nature walks and hikes. Explore the lush forests, pick berries or mushrooms, and immerse yourselves in the tranquility of the Karelian wilderness.",
        "Fishing and Canoeing: Gavo Shali is situated by a pristine lake, providing the opportunity for fishing or leisurely canoe trips. You can spend quality time together on the calm waters, perhaps even enjoying a picnic on a nearby island.",
        "Traditional Karelian Cuisine: The guesthouse offers delicious meals prepared with a focus on traditional Karelian cuisine. Savor the flavors of local dishes, and enjoy candlelit dinners in an intimate setting.",
        "Stargazing and Aurora Watching: The remote location and minimal light pollution make Gavo Shali an excellent place for stargazing and, during the right season, for watching the Northern Lights together.",
        "Gavo Shali in Karelia offers an ideal setting for couples looking to escape the hustle and bustle of everyday life and immerse themselves in the tranquility of Finnish nature. Whether it's enjoying a lakeside sauna, exploring the forests, or simply relishing each other's company in the cozy log cabins, Gavo Shali provides an intimate and romantic experience. Be sure to book your stay in advance, especially if you're planning a visit during the busy summer or Northern Lights season.",
      ],
    ),
    Place(
      id: '15',
      asset: 'assets/png/places/image16.png',
      name: 'Ukko-Koli - Koli National Park',
      rating: '2156 ratings',
      category: Category.romantic,
      content: [
        "Location: Koli National Park, Eastern Finland",
        "Description: Koli National Park, located in Eastern Finland, is home to the majestic Ukko-Koli hill and offers a serene and romantic getaway for couples who appreciate nature and breathtaking landscapes.",
        "Ukko-Koli Summit: Hike to the summit of Ukko-Koli hill, which provides panoramic views of Lake Pielinen and the surrounding wilderness. The vantage point offers an awe-inspiring vista that is perfect for sharing with your loved one.",
        "Scenic Trails: Koli National Park boasts an array of hiking trails that wind through pristine forests and along the picturesque shores of Lake Pielinen. Take a leisurely stroll along these trails, hand in hand, and enjoy the tranquility of the Finnish nature.",
        "Picnics and Campfires: Numerous designated picnic spots and campfire sites are available in the park. Bring a picnic basket and enjoy a romantic meal amidst the serene surroundings. Gather around a campfire for an intimate and cozy evening.",
        "Nature Observation Towers: Climb the observation towers in the park to get an even more stunning view of the landscape. This elevated perspective allows you to take in the beauty of the forests, lakes, and hills.",
        "Sunset and Sunrise Viewing: Ukko-Koli is a fantastic place to watch both sunsets and sunrises. The changing colors of the sky create an enchanting backdrop for romantic moments.",
        "Local Cuisine: Savor local Karelian cuisine at nearby restaurants, with dishes like Karelian pasties (karjalanpiirakka) and fish caught fresh from Lake Pielinen. These hearty meals can be enjoyed in a cozy, rustic setting.",
        "Koli National Park and Ukko-Koli hill provide couples with the perfect backdrop for a romantic escape in the heart of Finland's nature. Whether you're admiring the panoramic views, hiking the trails, or enjoying a meal in the Karelian tradition, you'll create cherished memories with your partner. Be sure to check the park's opening hours and trail conditions if you plan to visit during the winter months.",
      ],
    ),
    Place(
      id: '16',
      asset: 'assets/png/places/image17.png',
      name: 'Porvoo Island - Porvoo',
      rating: '315 ratings',
      category: Category.romantic,
      content: [
        "Location: Porvoo, Southern Finland",
        "Description: The charming town of Porvoo, located in Southern Finland, is home to a romantic gem known as Porvoo Island. This idyllic setting is perfect for couples seeking a romantic escape with a blend of history, culture, and natural beauty.",
        "Old Town of Porvoo: Begin your journey by exploring the Old Town of Porvoo, which is renowned for its well-preserved wooden houses, cobblestone streets, and scenic riverfront. Wander hand in hand through the charming streets, visiting local boutiques, art galleries, and quaint cafes.",
        "Porvoo Cathedral: The iconic Porvoo Cathedral, with its red façade, stands as a romantic backdrop for your visit. You can explore the cathedral and its surroundings, which are steeped in history and offer a sense of serenity.",
        "Riverside Views: Stroll along the riverside to enjoy picturesque views of the Porvoo River, the old warehouses, and the colorful buildings reflecting on the water. This tranquil setting is ideal for a leisurely walk with your loved one.",
        "Romantic Dining: Porvoo boasts a selection of charming restaurants and cafés where you can savor Finnish and international cuisine. Enjoy a romantic dinner with a view of the river, and perhaps indulge in local delicacies like salmon or crayfish.",
        "Porvoo Art Factory: The Porvoo Art Factory (Taidetehdas) is a cultural hub that often hosts art exhibitions, live performances, and events. Check the calendar to see if there's a concert, theater show, or exhibition that you and your partner can attend together.",
        "Sunsets and Photography: The picturesque setting of Porvoo Island is perfect for capturing romantic moments on camera. Be sure to watch the sun setting over the river and snap some photos of the stunning views.",
        "Porvoo Island in the historic town of Porvoo is a delightful destination for couples seeking a romantic blend of history, culture, and natural beauty. Whether you're exploring the Old Town, enjoying riverside strolls, or indulging in delicious cuisine, you'll create lasting memories in this enchanting location. Check the opening hours of local establishments and any cultural events happening during your visit to enhance your experience.",
      ],
    ),
    Place(
      id: '17',
      asset: 'assets/png/places/image18.png',
      name: 'Långvik Hotel and Spa - Espoo',
      rating: '542 ratings',
      category: Category.romantic,
      isPremium: true,
      content: [
        "Location: Espoo, Greater Helsinki",
        "Description: Långvik Hotel and Spa is a luxurious and romantic escape located along the shores of the Gulf of Finland, just outside of Helsinki. This upscale destination provides couples with an opportunity for relaxation, rejuvenation, and fine dining.",
        "Scenic Coastal Views: The hotel is situated by the sea, offering breathtaking views of the Gulf of Finland. You and your partner can enjoy the ever-changing sea vistas from your room, the spa, and various relaxation areas.",
        "Spa and Wellness: Långvik boasts an extensive spa and wellness center, which includes saunas, pools, and a variety of treatments. Indulge in couples' massages or simply unwind in the serene spa facilities.",
        "Culinary Delights: The hotel's gourmet restaurant serves delectable Finnish and international dishes prepared with a focus on seasonal and locally sourced ingredients. Share a romantic meal with a view of the sea.",
        "Private Saunas: Many rooms and suites at Långvik include their own private saunas. After a day of relaxation, you and your partner can enjoy a peaceful and intimate sauna experience.",
        "Nature Walks: The hotel is surrounded by beautiful nature, including walking paths along the coast and through the nearby woods. Take a romantic stroll together and connect with the natural world.",
        "Wellness Classes: The hotel often offers wellness classes, including yoga and meditation sessions. Participate in these classes to rejuvenate and connect on a deeper level with your partner.",
        "Outdoor Terraces: Enjoy the outdoors on the hotel's outdoor terraces. You can have a drink, read a book, or simply bask in the tranquility of the Gulf of Finland.",
        "Långvik Hotel and Spa in Espoo is a haven for couples looking for a romantic retreat with a focus on relaxation, wellness, and fine dining. The serene coastal setting, spa facilities, and exceptional cuisine provide an excellent backdrop for creating lasting romantic memories. Be sure to book spa treatments and dining reservations in advance, especially during peak seasons.",
      ],
    ),
    Place(
      id: '18',
      asset: 'assets/png/places/image19.png',
      name: 'Starry Nights and Northern Lights in Lapland',
      rating: '6594 ratings',
      category: Category.romantic,
      isPremium: true,
      content: [
        "Location: Various locations in Lapland, such as Rovaniemi, Levi, and Inari.",
        "Description: Lapland, located in the northernmost reaches of Finland, is not only famous for its snowy landscapes but also for offering couples the opportunity to experience the magic of starry nights and the Northern Lights. It's a romantic destination where you can bond under the celestial wonders of the Arctic skies.",
        "Aurora Borealis Tours: Lapland is one of the best places on Earth to witness the Northern Lights. Consider booking an Aurora Borealis tour with local guides who can take you to the best viewing spots and provide insights into this natural phenomenon.",
        "Cozy Accommodations: Lapland offers various accommodation options, including glass igloos, log cabins, and wilderness lodges. These cozy and secluded settings allow you and your partner to gaze at the night sky from the warmth and comfort of your own private space.",
        "Photography Opportunities: If you both love photography, the Northern Lights present a wonderful opportunity to capture the awe-inspiring light show on camera. Share the excitement of capturing these unique moments together.",
        "Warm Saunas and Hot Tubs: After a night of Northern Lights viewing, unwind in a traditional Finnish sauna or relax in an outdoor hot tub. The contrast of the cold Arctic air and the soothing warmth of a sauna or hot tub can be an intimate and memorable experience.",
        "Arctic Experiences: Participate in thrilling Arctic adventures, such as husky sledding, snowmobiling, and reindeer sleigh rides. These activities are not only exciting but also create lasting memories as you experience the Arctic together.",
        "Local Sami Culture: Lapland is also home to the indigenous Sami people. Immerse yourselves in Sami culture by visiting a traditional reindeer farm or joining cultural experiences led by Sami guides.",
        "Romantic Dining: Savor Finnish and Sami cuisine at local restaurants. Enjoy Arctic delicacies like smoked salmon and hearty stews in a cozy and romantic dining setting.",
        "Lapland's starry nights and Northern Lights offer couples a truly magical and romantic experience. Whether you're witnessing the Aurora Borealis, exploring the Arctic wilderness, or enjoying a relaxing soak in a hot tub, Lapland provides an enchanting backdrop for creating unforgettable memories with your loved one. Be sure to plan your trip during the prime Northern Lights season, which typically falls between late autumn and early spring.",
      ],
    ),
    Place(
      id: '19',
      asset: 'assets/png/places/image20.png',
      name: 'Sunset at Lake Inari - Inar',
      rating: '3413 ratings',
      category: Category.romantic,
      isPremium: true,
      content: [
        "Location: Inari, Lapland",
        "Description: Watching the sunset over Lake Inari, located in the heart of Lapland, is a romantic experience like no other. It offers couples a serene and awe-inspiring natural setting to connect and create lasting memories.",
        "Lake Inari: Lake Inari is Finland's third-largest lake, known for its crystal-clear waters and surrounded by pristine wilderness. It is a place of incredible natural beauty and serenity.",
        "Sunset Views: As the sun begins to set over Lake Inari, the sky transforms into a mesmerizing canvas of colors. The reflections on the water create a breathtaking, ever-changing panorama.",
        "Private Moments: The secluded nature of Lake Inari means you and your partner can have private moments by the lake's shore, on the beach, or even from the balcony of your accommodation.",
        "Activities: Lake Inari offers opportunities for fishing, boating, and hiking. You can engage in these activities together during the day and then unwind with a romantic sunset in the evening.",
        "Northern Lights Potential: If you visit during the right season, Lake Inari is also a great place to witness the Northern Lights. The celestial show adds an extra layer of magic to your evening.",
        "Local Culture: Inari is home to the indigenous Sami people. Consider visiting the Siida Sami Museum and Nature Center to learn about their culture and traditions.",
        "Camping and Accommodations: The area around Lake Inari offers various accommodation options, from camping sites to cabins and lodges. Spend a night camping under the starry sky or in a cozy cabin by the lakeshore.",
        "Night Photography: If you're interested in photography, the unique lighting during the sunset hours and the possibility of capturing the Northern Lights make Lake Inari a wonderful destination for night photography.",
        "Quiet Moments: Lake Inari is renowned for its peace and quiet, making it the perfect setting to unwind, reflect, and connect with your partner.",
        "Watching the sunset at Lake Inari is a truly romantic and tranquil experience, where you can immerse yourselves in the natural beauty of Lapland and enjoy the quiet moments of serenity together. Whether you're enjoying the vibrant sunset or the possibility of the Northern Lights, Lake Inari offers an unforgettable setting for a romantic getaway. Be sure to check the best time to visit for optimal sunset viewing and, if desired, Northern Lights sightings.",
      ],
    ),
    Place(
      id: '20',
      asset: 'assets/png/places/image21.png',
      name: 'Ukko-Koli Summit - Koli National Park',
      rating: '3251 ratings',
      category: Category.fromOnHigh,
      content: [
        "Location: Koli National Park, Eastern Finland",
        "Description: The Ukko-Koli summit, also known as Koli's crown, is the highest point in Koli National Park. Rising 347 meters above sea level, it offers spectacular panoramic views of Lake Pielinen and the surrounding Karelian landscape.",
        "Hiking Trails: There are well-maintained hiking trails leading to the summit, making it accessible for visitors of various fitness levels. The most popular trail, the Paha-Koli trail, takes you to the top where you'll find a viewing platform. Along the way, you'll pass through lush forests, rocky terrain, and serene ponds.",
        "Viewing Platforms: At the summit, you'll find a viewing platform that provides an uninterrupted view of Lake Pielinen, which is one of Finland's largest and most picturesque lakes. The vistas are particularly stunning during sunrise and sunset, creating a magical atmosphere for couples.",
        "Photography Opportunities: The breathtaking scenery at Ukko-Koli is a photographer's dream. Capturing the changing colors of the landscape and the play of light on the lake can be a romantic activity for couples who enjoy photography.",
        "All-Season Destination: Ukko-Koli is a year-round destination. In the summer, the landscape is lush and green, while the winter brings a snowy wonderland. Each season offers a unique perspective and charm.",
        "Cultural Significance: Koli is often associated with Finnish national identity and has inspired numerous artists and writers. It's a place where you can immerse yourself in Finnish culture and natural beauty.",
        "Accommodations: There are various accommodations available in Koli National Park, including cabins, cottages, and hotels. Many of them offer stunning views of the surrounding landscape, making it a romantic place to stay.",
        "The Ukko-Koli summit is a captivating and romantic destination in Koli National Park, perfect for couples who enjoy outdoor activities and breathtaking natural vistas. Whether you're hiking to the summit, taking in the stunning views, or capturing the beauty through photography, this location provides a truly memorable experience. Be sure to check the park's opening hours and trail conditions based on the season of your visit.",
      ],
    ),
    Place(
      id: '21',
      asset: 'assets/png/places/image22.png',
      name: 'Oulanka National Park Cliffs - Oulanka National Park',
      rating: '612 ratings',
      category: Category.fromOnHigh,
      content: [
        "Location: Oulanka National Park, Northern Finland",
        "Description: Oulanka National Park is renowned for its rugged landscapes and pristine natural beauty. Among its many wonders are the towering cliffs and rock formations, which provide awe-inspiring panoramic views of the park's wild rivers and deep forests.",
        'Cliffs and Rock Formations: Oulanka National Park is home to several cliffs and rock formations, such as "Pedatsekka" and "Mertsökulma." These dramatic geological features offer an excellent vantage point for observing the untouched wilderness.',
        "River Views: From these cliffs, you can gaze down upon the tumultuous waters of the Oulanka River. The river winds its way through the park, and the views of the rushing water and surrounding forests are nothing short of magnificent.",
        "Hiking Trails: Many hiking trails in the park will take you to these cliffside viewpoints. These trails meander through the unspoiled landscapes, providing a perfect opportunity to reconnect with nature and each other.",
        "Photography Opportunities: Oulanka National Park is a paradise for nature photographers. The dramatic cliffs and the pristine natural surroundings offer an abundance of photography opportunities for couples who love to capture the beauty of the outdoors.",
        "Seasonal Beauty: The park's scenery changes with the seasons. In the summer, it's lush and vibrant, while the autumn offers a colorful display of foliage. Winter brings a tranquil, snow-covered wonderland. No matter when you visit, you'll be treated to a unique visual spectacle.",
        "Wildlife Watching: Oulanka National Park is also a great place for wildlife enthusiasts. While enjoying the views from the cliffs, you may spot various animal species that call the park home, from reindeer to birds of prey.",
        "Accommodations: There are accommodations within or near the park, ranging from wilderness cabins to guesthouses. These provide comfortable and romantic places to stay while immersing yourselves in the natural wonders of the park.",
        "The cliffs and rock formations in Oulanka National Park offer a captivating and romantic setting for couples who appreciate the wild beauty of untouched nature. Whether you're hiking the trails, taking in the breathtaking views, or trying to capture the pristine landscapes through photography, you'll experience an unforgettable connection with nature. Be sure to check the park's hours and trail conditions according to the season you plan to visit.",
      ],
    ),
    Place(
      id: '22',
      asset: 'assets/png/places/image23.png',
      name: 'Taivaskallio Cliffs - Helsinki',
      rating: '2487 ratings',
      category: Category.fromOnHigh,
      content: [
        "Location: Taivaskallio Cliffs, Helsinki, Southern Finland",
        "Description: Taivaskallio Cliffs, located just outside the capital city of Helsinki, is a picturesque spot offering breathtaking views of the Baltic Sea and the archipelago. This location is an easily accessible escape for couples seeking both natural beauty and urban convenience.",
        "Spectacular Coastal Views: Taivaskallio provides an exceptional vantage point to take in the panoramic views of the Baltic Sea and the archipelago islands. The combination of the sea, the rugged cliffs, and the serene surroundings creates a romantic atmosphere.",
        "Hiking and Nature Walks: The area around Taivaskallio offers various trails, making it a delightful spot for a leisurely hike or a peaceful nature walk. These trails take you through lush forests and open meadows with the promise of picturesque viewpoints.",
        "Picnics and Relaxation: Many visitors bring along a picnic to enjoy on the cliffs. The tranquil setting is perfect for unwinding with your partner, whether you're enjoying a meal, reading a book, or simply basking in the natural surroundings.",
        "Sunsets and Sunrise: Taivaskallio is an excellent place to witness beautiful sunsets and sunrises. The changing colors of the sky and the reflection on the sea create a romantic atmosphere for couples to relish.",
        "Cultural Experience: You can combine your visit to Taivaskallio with a trip to the nearby Seurasaari Open-Air Museum, which provides a glimpse into traditional Finnish life. It's an educational and culturally enriching experience.",
        "Convenient Location: The proximity of Taivaskallio to Helsinki makes it an ideal day trip destination. After enjoying the views, you can explore the vibrant city for a romantic dinner or other cultural activities.",
        "Romantic Photography: The stunning scenery at Taivaskallio is a photographer's dream. Capturing the changing colors of the sky and the sea can be a shared and memorable activity for couples.",
        "Taivaskallio Cliffs offer a serene and romantic getaway just outside the bustling city of Helsinki. Whether you're admiring the coastal views, exploring the trails, or enjoying a picnic, you'll create cherished memories with your partner. Be sure to check the opening hours of the nearby museum and the best times for sunset and sunrise viewing to enhance your experience.",
      ],
    ),
    Place(
      id: '23',
      asset: 'assets/png/places/image24.png',
      name: 'Hankivuori Hill - Southern Savonia',
      rating: '236 ratings',
      category: Category.fromOnHigh,
      content: [
        "Location: Hankivuori Hill, Southern Savonia, Eastern Finland",
        "Description: Hankivuori Hill is a scenic destination in Southern Savonia, Eastern Finland, known for its panoramic views and rugged landscapes. It provides a romantic escape for couples looking to connect with nature and each other.",
        "Spectacular Hilltop Views: Hankivuori Hill offers stunning 360-degree panoramic views of the surrounding landscapes, including rolling hills, serene lakes, and lush forests. The vastness of the scenery makes it a captivating spot for couples.",
        "Hiking Opportunities: The hill is accessible via well-marked hiking trails that wind their way through the pristine wilderness. The journey to the summit is an adventure in itself, surrounded by the sights and sounds of the Finnish countryside.",
        "Wildflowers and Wildlife: Hankivuori Hill is known for its diverse flora and fauna. Depending on the season of your visit, you may encounter wildflowers, migratory birds, or the vibrant colors of autumn foliage.",
        "Picnics and Relaxation: The hilltop is a great place for a picnic or a moment of relaxation. Bring along a picnic basket, enjoy a meal with your loved one, and immerse yourselves in the serene natural beauty.",
        "Sunset and Sunrise Viewing: The hill's elevated location makes it a wonderful place to watch the sun set or rise. The changing colors of the sky create a romantic backdrop for your moments together.",
        "Local Cuisine: After your hike, you can explore the nearby towns and enjoy traditional Finnish cuisine. Many local restaurants offer a chance to savor regional dishes and fresh, locally sourced ingredients.",
        "Star Gazing: The remote location of Hankivuori Hill, away from the city lights, makes it an excellent spot for stargazing. Lay a blanket on the ground and admire the clear night skies with your partner.",
        "Hankivuori Hill in Southern Savonia provides couples with a tranquil and romantic setting to explore nature and relish stunning vistas. Whether you're hiking to the summit, having a picnic, or stargazing, this location offers a unique connection with the natural world. Be sure to check trail conditions, seasonal highlights, and local dining options for a well-rounded experience.",
      ],
    ),
    Place(
      id: '24',
      asset: 'assets/png/places/image25.png',
      name: 'Fullerönselkä - Åland Archipelago',
      rating: '237 ratings',
      category: Category.fromOnHigh,
      content: [
        "Location: Fullerönselkä, Åland Archipelago, Southwestern Finland",
        "Description: Fullerönselkä is a breathtaking viewpoint in the Åland Archipelago, providing couples with remarkable vistas of the Baltic Sea and the stunning archipelago islands. This location offers a tranquil escape amidst nature's beauty.",
        "Stunning Archipelago Views: Fullerönselkä offers unobstructed, panoramic views of the Baltic Sea, dotted with countless islands. The unique charm of the Åland Archipelago, characterized by rocky shores and serene waters, creates a romantic and picturesque setting.",
        "Hiking Trails: The viewpoint is accessible via well-marked hiking trails. These trails take you through the archipelago's lush forests and meadows, enhancing your connection with nature as you make your way to the top.",
        "Birdwatching: The Åland Archipelago is home to diverse birdlife. Birdwatching can be an engaging and romantic activity for couples as you observe various species in their natural habitat.",
        "Picnics and Relaxation: The hilltop at Fullerönselkä is perfect for picnics and relaxation. Bring along a picnic basket with local delicacies, enjoy a meal together, and savor the tranquil surroundings.",
        "Sunset and Sunrise Views: The elevated location offers fantastic opportunities to watch the sun set or rise over the archipelago, casting mesmerizing colors over the sea and islands.",
        "Cultural Exploration: After your hike, you can explore the charming villages and towns on Åland, each with its unique cultural heritage. Visit local museums, art galleries, and boutiques to enrich your experience.",
        "Accommodations: You'll find a range of accommodations on the Åland Islands, from cozy cottages to boutique hotels. These provide a comfortable and romantic base for exploring the archipelago.",
        "Fullerönselkä in the Åland Archipelago offers couples an enchanting and serene getaway surrounded by the natural beauty of the archipelago. Whether you're hiking the trails, indulging in a picnic, or witnessing the magical sunsets and sunrises, this location presents a unique connection with the captivating Åland Islands. Be sure to check the trail conditions and explore the nearby cultural attractions to make the most of your visit.",
      ],
    ),
    Place(
      id: '25',
      asset: 'assets/png/places/image26.png',
      name: 'Ylläs - Lapland',
      rating: '167 ratings',
      category: Category.fromOnHigh,
      content: [
        "Location: Ylläs, Lapland, Northern Finland",
        "Description: Ylläs is a stunning region in Lapland, Northern Finland, known for its breathtaking vistas of rugged mountains, pristine forests, and the Northern Lights. It's a romantic destination for couples seeking a unique connection with nature and Lapland's wonders.",
        "Lapland's Rugged Beauty: Ylläs showcases the untamed beauty of Lapland. The landscape features expansive fells, dense forests, and tranquil lakes, making it a perfect backdrop for romantic adventures.",
        "Hiking Trails: Ylläs offers a network of well-maintained hiking trails that lead you through the wilderness. Whether you prefer gentle strolls or more challenging hikes, there are paths suitable for every level.",
        "Aurora Borealis: Ylläs is one of the best places to witness the Northern Lights in Finland. The enchanting dance of colors in the night sky creates a magical and unforgettable experience for couples.",
        "Reindeer Encounters: Lapland is home to reindeer, and you may come across these gentle creatures as you explore the area. Many local experiences offer the chance to interact with and learn about these iconic animals.",
        "Lapland Culture: Ylläs provides insights into the unique culture of Lapland. Visit traditional Sámi villages, learn about Sámi traditions, and explore local handicrafts and cuisine to enrich your experience.",
        "Winter Wonderland: Ylläs is equally enchanting in the winter. Engage in activities like cross-country skiing, snowshoeing, and dog sledding for a memorable winter adventure.",
        "Accommodations: The region offers various accommodations, from cozy cabins to boutique hotels and glass igloos. These provide comfortable and romantic places to stay while exploring the wonders of Lapland.",
        "Ylläs in Lapland is an awe-inspiring and romantic destination for couples to immerse themselves in the pristine beauty of the Arctic wilderness. Whether you're hiking the trails, witnessing the Northern Lights, or exploring Lapland's unique culture, this location offers a profound connection with the natural and cultural wonders of Lapland. Be sure to check trail conditions, Northern Lights forecasts, and seasonal highlights to make the most of your visit.",
      ],
    ),
    Place(
      id: '26',
      asset: 'assets/png/places/image27.png',
      name: 'Vuorimaa - Porvoo',
      rating: '4954 ratings',
      category: Category.fromOnHigh,
      content: [
        "Location: Vuorimaa, Porvoo, Southern Finland",
        "Description: Vuorimaa is a hilly and picturesque area near the town of Porvoo, in Southern Finland. This location offers couples a romantic retreat with its rolling landscapes and stunning panoramic views.",
        "Hilltop Views: Vuorimaa features a range of gentle hills and elevated spots that provide commanding vistas of the surrounding countryside. You'll be treated to sweeping views of fields, forests, and the town of Porvoo in the distance.",
        "Hiking and Nature Walks: The hilly terrain of Vuorimaa is ideal for hiking and nature walks. You can explore various trails that meander through lush greenery and quiet meadows, adding an element of adventure to your romantic escape.",
        "Wildflower Season: Depending on the time of year, you might encounter vibrant wildflowers and blossoms that adorn the landscape, creating a colorful and romantic setting for your walks.",
        "Picnics and Relaxation: The hilltops in Vuorimaa are great spots for a picnic or simply to relax and take in the peaceful surroundings. You can bring a basket with local goodies and enjoy a meal with your loved one.",
        "Sunset and Sunrise Views: Vuorimaa's elevated location offers excellent opportunities for watching the sun set or rise over the Finnish countryside. The changing hues of the sky and the tranquil atmosphere make it a perfect setting for a romantic moment.",
        "Local Culture: After your outdoor adventures, you can explore the charming town of Porvoo with its well-preserved historic buildings and cultural attractions. Discover local art, museums, and quaint cafes to enhance your visit.",
        "Accommodations: Porvoo offers a range of accommodations, from cozy guesthouses to boutique hotels. You can find comfortable and romantic places to stay while exploring Vuorimaa and the town.",
        "Vuorimaa in Porvoo provides couples with a serene and romantic escape, where you can connect with nature and each other. Whether you're hiking the trails, enjoying a picnic, or witnessing the breathtaking sunsets and sunrises, this location offers a unique opportunity to create lasting memories. Be sure to check the trail conditions and explore the nearby cultural attractions in Porvoo for a well-rounded experience.",
      ],
    ),
    Place(
      id: '27',
      asset: 'assets/png/places/image28.png',
      name: 'Kuopio Puijo Viewing Tower - Kuopio',
      rating: '8263 ratings',
      category: Category.fromOnHigh,
      isPremium: true,
      content: [
        "Location: Kuopio Puijo Viewing Tower, Kuopio, Eastern Finland",
        "Description: The Kuopio Puijo Viewing Tower is an iconic landmark that offers couples breathtaking views of Lake Kallavesi, the city of Kuopio, and the surrounding Finnish lakeland landscapes.",
        "Panoramic Lake Views: From the viewing tower, you'll enjoy expansive views of Lake Kallavesi, which is one of Finland's largest and most picturesque lakes. The surrounding lakeland region, with its countless lakes and lush forests, adds to the visual splendor.",
        "Hiking Trails: The area around Puijo offers hiking trails of varying lengths and difficulty levels. These trails wind through the verdant landscapes, providing a romantic opportunity for couples to connect with nature.",
        "Picnics and Relaxation: The hilltop of Puijo is a perfect place for a picnic. You can bring along a picnic basket filled with local delicacies, enjoy a meal together, and bask in the serene surroundings.",
        "Sunset and Sunrise Views: The elevated location of Puijo makes it an ideal spot for watching stunning sunsets and sunrises. The changing colors of the sky and the reflection on the lakes create a magical atmosphere for couples.",
        "Local Cuisine: After your outdoor activities, you can explore the town of Kuopio, renowned for its local cuisine. Try regional dishes and fresh, locally sourced ingredients at local restaurants to enhance your experience.",
        "Winter Activities: Puijo is also a popular destination in the winter. You can engage in activities like cross-country skiing or snowshoeing, making your visit to Puijo equally enchanting in the colder months.",
        "Accommodations: Kuopio offers a range of accommodations, from modern hotels to charming guesthouses. These provide comfortable and romantic places to stay while exploring Puijo and the city.",
        "The Kuopio Puijo Viewing Tower invites couples to savor the beauty of the Finnish lakeland region from a unique perspective. Whether you're hiking the trails, enjoying a picnic, or witnessing the enchanting sunsets and sunrises, this location offers a memorable connection with the serene landscapes of Eastern Finland. Be sure to check the trail conditions and explore the local dining options to make the most of your visit.",
      ],
    ),
    Place(
      id: '28',
      asset: 'assets/png/places/image29.png',
      name: 'Patkankangas Viewing Tower - Kainuu',
      rating: '1526 ratings',
      category: Category.fromOnHigh,
      isPremium: true,
      content: [
        "Location: Patkankangas Viewing Tower, Kainuu, Northern Finland",
        "Description: The Patkankangas Viewing Tower is a spectacular observation point in the region of Kainuu in Northern Finland. It provides couples with remarkable views of the vast forests and pristine nature that define this part of the country.",
        "Aerial Perspective of Kainuu: From the Patkankangas Viewing Tower, you'll be treated to an aerial view of Kainuu's endless forests, tranquil lakes, and untouched wilderness. The bird's-eye perspective creates a sense of awe and serenity.",
        "Forest Hiking: The area around the tower is perfect for hiking in the midst of the boreal forest. Take a romantic stroll together along the well-maintained trails, surrounded by the beauty of the northern woods.",
        "Wildlife Encounters: Kainuu is known for its diverse wildlife, and you might spot animals such as reindeer, elk, and various bird species. Wildlife watching can be an engaging and memorable activity for couples.",
        "Birdwatching: Bird enthusiasts will have a great time spotting various bird species that inhabit the area. Bring binoculars for a closer look at the feathered inhabitants of the forest.",
        "Picnics and Relaxation: The vicinity of the Patkankangas Viewing Tower is an ideal place for a picnic. Pack a basket with local delicacies, savor a meal, and take in the tranquil atmosphere of the woods.",
        "Cultural Exploration: After your forest adventures, you can explore the local culture in Kainuu. Learn about the region's heritage and traditional practices through local museums and cultural activities.",
        "Accommodations: Kainuu offers various accommodations, from rustic cabins to comfortable lodges. These options provide cozy and romantic places to stay while immersing yourself in the natural beauty of the region.",
        "The Patkankangas Viewing Tower in Kainuu is a captivating and romantic destination for couples seeking a deeper connection with the untouched nature of Northern Finland. Whether you're hiking the forest trails, observing wildlife, or enjoying a peaceful picnic, this location offers an extraordinary opportunity to create lasting memories. Be sure to check trail conditions and explore local cultural attractions for a well-rounded experience.",
      ],
    ),
    Place(
      id: '29',
      asset: 'assets/png/places/image30.png',
      name: 'Korppoo Viewing Tower - Turku Archipelago',
      rating: '845 ratings',
      category: Category.fromOnHigh,
      isPremium: true,
      content: [
        "Location: Korppoo Viewing Tower, Turku Archipelago, Southwestern Finland",
        "Description: The Korppoo Viewing Tower is an exceptional vantage point situated in the Turku Archipelago, offering couples breathtaking views of the Baltic Sea, the archipelago's islands, and the rugged coastline.",
        "Spectacular Coastal Views: The viewing tower provides uninterrupted, panoramic views of the Baltic Sea and the countless islands that make up the Turku Archipelago. The stark beauty of the rocky shores and tranquil waters sets the stage for a romantic experience.",
        "Hiking Trails: The area surrounding the tower features hiking trails that guide you through the archipelago's unique landscapes, where you'll encounter rocky cliffs, forested paths, and open meadows.",
        "Birdwatching: The Turku Archipelago is a haven for birdwatching, and you can observe various bird species in their natural habitat. Bring binoculars and take the time to appreciate the avian wonders of the region.",
        "Picnics and Relaxation: The tower's vicinity is an ideal spot for a picnic. Bring a picnic basket filled with local treats, dine with your loved one, and enjoy the tranquility of the archipelago's scenery.",
        "Sunsets and Sunrise Viewing: The elevated position of the Korppoo Viewing Tower allows you to savor mesmerizing sunsets and sunrises. The shifting hues of the sky and the reflection on the sea create a romantic backdrop for your moments together.",
        "Local Culture: After exploring the archipelago's natural beauty, venture into the charming villages and towns to learn about local customs and heritage. Visit cultural attractions, art galleries, and local markets to enhance your experience.",
        "Accommodations: The Turku Archipelago offers a variety of accommodations, from cozy cottages to boutique inns. These options provide comfortable and romantic places to stay while exploring the archipelago.",
        "The Korppoo Viewing Tower in the Turku Archipelago invites couples to immerse themselves in the archipelago's rugged beauty and pristine natural settings. Whether you're hiking the trails, watching birds, or enjoying a picnic, this location provides a unique opportunity to connect with the captivating Turku Archipelago. Be sure to check the trail conditions and explore the local cultural attractions for a well-rounded experience.",
      ],
    ),
    Place(
      id: '30',
      asset: 'assets/png/places/image31.png',
      name: 'Rax Buffet',
      rating: '15215 ratings',
      category: Category.eat,
      content: [
        "So, the first place where we will refresh ourselves will be the Rax Buffet restaurant, where a simple buffet awaits us. The restaurant's menu offers: soups, salads, pizzas, desserts, drinks. It is worth saying that the soup there is a little thick, but it is served on Finnish crispy buns. Buffet (adults) 9.95 euros. Buffet for children (under 7 years old) 3.95 euros. Buffet for children (up to 12 years old) 6.95 euros. Takeaway food (salad, pizza and hot food) 1.95 euros per 100g. Takeaway pizza (small/large, choice of two toppings) 6.90 / 13.90 euros. Create your own pizza (choice of three toppings) buffet + 3 euros. Students receive a 10% discount on the regular price, but you must present your student ID. Addresses: Mikonkatu 8 (opening hours: Mon-Sat 11.00 - 21.00, Sunday 12.00 - 21.00) Turunlinnantie 6 (opening hours: Mon-Fri from 11.00 - 21.00, Saturday from 11.00 - 19.00, Sunday from 12.00 - 19.00).",
      ],
    ),
    Place(
      id: '31',
      asset: 'assets/png/places/image32.png',
      name: 'Lappi Ravintola',
      rating: '3251 ratings',
      category: Category.eat,
      content: [
        "On Annankatu street there is a nice restaurant called Lappi. Traditional Finnish cuisine is widely represented here (fish soups, venison, homemade Lapland bread....) Be sure to try venison with lingonberry sauce when you are in Lappi. The menu includes roasted venison, homemade wine and coffee served in a wooden mug called a kuksa. Overall, very pleasant cuisine, interior and atmosphere. Lappi is the oldest Lappish restaurant in Helsinki. This restaurant has a group menu, here are its conditions: the group size must include at least 6 people and everyone must choose the same menu. Order confirmation must be made in advance, no later than 3 days. ddress: Annankatu 22. Opening hours: Mon-Fri from 12.00 - 00.00, on Saturdays from 13.00 - 00.00, Sunday - closed.Подробнее: https://e-finland.ru/rest/all-year/restorany-helsinki-gde-mozhno-vkusno-i-nedorogo-poest.html",
      ],
    ),
    Place(
      id: '32',
      asset: 'assets/png/places/image33.png',
      name: 'Kappeli',
      rating: '1525 ratings',
      category: Category.eat,
      content: [
        "And for a special atmosphere you should go to Kappeli. This stylish, glass-walled restaurant has been a landmark of the Esplanadi since 1867. This establishment has been keeping traditions for 147 years, but not so long ago it was closed for a two-month renovation, but today it can be seen in its updated interior. An interesting fact from the past is that tea with vodka was served here in 1919, as prohibition was in effect in Finland at that time. And today, here you can not only eat delicious food, but also immerse yourself in the atmosphere of old Helsinki. But it is worth warning that immersing yourself in the atmospheric Helsinki will not be so cheap, on average the price per dish reaches 20 euros, but it is still worth coming here, even if only to drink a cup of coffee. The establishment is located at Eteläesplanadi 1, open daily from 09.00-00.00.",
      ],
    ),
    Place(
      id: '33',
      asset: 'assets/png/places/image34.png',
      name: 'Iguana',
      rating: '1525 ratings',
      category: Category.eat,
      content: [
        "The next point on our culinary journey is the chain Mexican restaurant Iguana. A pleasant restaurant with a unique atmosphere and good cuisine. If you're passing by, be sure to stop by. The menu has many options for pizzas, pastas and salads. The price for lunch from 12.00 to 16.00 will be 14.90 euros. Restaurants are located at: Mannerheimintie 12, Keskuskatu 4, Kaisaniemenkatu 3. Opening hours: Mon-Fri from 11.00 - 00.00, on Saturday from 12.00 - 02.00, on Sunday from 12.00 - 00.00."
      ],
    ),
    Place(
      id: '34',
      asset: 'assets/png/places/image35.png',
      name: 'Santa Fe',
      rating: '5126 ratings',
      category: Category.eat,
      content: [
        "This is a cozy Mexican restaurant where you can truly immerse yourself in the culture of this mysterious country. The restaurant's cuisine is very extensive, representing both Mexican and international cuisine. In the summer, there is live music from Monday to Thursday, performed by various groups. Average. one dish will cost approximately 15 euros. But from 11.00 to 15.00 you can enjoy lunch, which will cost less, about 10 euros. The restaurant is located at: Aleksanterinkatu 15, opening hours: Mon-Thu from 11.00 - 00.00, Fri-Sat from 11.00 - 02.00, Sunday from 13.00 - 00.00.",
      ],
    ),
    Place(
      id: '35',
      asset: 'assets/png/places/image36.png',
      name: 'Bistro Belge',
      rating: '475 ratings',
      category: Category.eat,
      content: [
        "Belgian restaurant. If you consider yourself a gourmet and want to taste something truly special, then you should definitely visit this restaurant, but keep in mind that the prices here are very undemocratic. The only time when you can save money here is from 11.00 to 15.00, but strictly on weekdays, lunch will cost only 10 euros. This establishment is notable for its interior; photographs of Belgian queens and kings are posted on the walls, so you can feel the spirit of Belgian history in Helsinki. The establishment is located at: Kluuvikatu 5, opening hours: Mon-Tue 11:00-00:00, Wed-Thu 11:00-2:00, Fri-Sat 11:00-4:00, Sun 12:00-00 :00",
      ],
    ),
    Place(
      id: '36',
      asset: 'assets/png/places/image37.png',
      name: 'Fazer Cafe',
      rating: '823 ratings',
      category: Category.eat,
      content: [
        "You won't regret visiting Fazer Cafe. Pleasant atmosphere, wide selection of snacks, huge assortment of cakes and all kinds of sweets. If you wish, you can take wine or beer. Well, if you are hungry, you can refresh yourself by taking advantage of the buffet offer. The cafe is in the very center and very easy to find. Located at Kluuvikatu 3, opening hours: Mon-Fri from 07.30 - 22.00, Saturday from 09.00 - 22.00, Sunday from 10.00 - 18.00. You can wander the streets of Helsinki for a long time and discover wonderful cafes and restaurants. Among the city's restaurants there are first-class gourmet restaurants, restaurants with national cuisine and small bistros. There is always a lot of fresh vegetables, berries, mushrooms and, of course, fish. The Finns themselves recommend trying seasonal delicacies when in Helsinki: January - Burbot with caviar and pancakes. February - Runeberg cake, pea soup and Pancake Day buns. March-April - Lamb, mämmi (dessert made from rye flour with malt), paskha (Easter cottage cheese). May - Perch, whitefish, pike perch, Sima honey drink with “brushwood”. June-July - New potatoes, salmon, sausage, herring, strawberries, blueberries, cloudberries. August - Vegetables, crayfish, duck, chanterelles, apples. September - Herring, vendace, hare, funnel-headed chanterelles, lingonberries. October-November - Lamb, cabbage, elk, venison, goose. December - Ham, rosolli, pureed vegetables, ginger biscuits, Christmas cakes, gleg. But wherever you go, you can be sure that everywhere you will find the true philosophy of Finnish cuisine , which is based on the environmental purity and freshness of the products used to prepare dishes.",
      ],
    ),
    Place(
      id: '37',
      asset: 'assets/png/places/image38.png',
      name: 'Cafe Ekberg',
      rating: '7890 ratings',
      category: Category.eat,
      isPremium: true,
      content: [
        "The oldest bakery in the capital of Finland has been in existence since 1852. In addition to the most delicious cakes and pastries, you can have an inexpensive breakfast and lunch here.",
        "Breakfast is presented as a buffet with a wide range of dishes. Every day (except weekends) a visit to the cafe until 10.30 costs 11.5 euros. On weekends, breakfast costs a little more - about 18 euros. Bakery address: Bulevardi 9.",
      ],
    ),
    Place(
      id: '38',
      asset: 'assets/png/places/image39.png',
      name: 'Momotoko',
      rating: '864 ratings',
      category: Category.eat,
      isPremium: true,
      content: [
        "There is a cafe with Asian cuisine next to the Athenaeum Museum and the University of Helsinki (Yliopistonkatu, 5). From 11.00 to 14.00 a lunch menu is available to visitors. During this time, chicken teriyaki with vegetables costs 11.50 euros, and vegetarian chilli ramen can be enjoyed for just 10 euros. After 14.00 and until 17.00, all dishes from the lunch menu have a fixed price of 12 euros. The cafe also has a regular menu; dishes from it cost 15-16 euros.",
      ],
    ),
    Place(
      id: '39',
      asset: 'assets/png/places/image40.png',
      name: 'Cafe Bar No 9',
      rating: '673 ratings',
      category: Category.eat,
      isPremium: true,
      content: [
        "The cafe is located near Esplanade Park (Uudenmaankatu, 9) and differs from all nearby establishments in its large portions at affordable prices. Caesar salad with chicken or salmon costs 12-13.5 euros. You can taste the first course for only 10 euros. The cafe menu includes various burgers, costing from 10 euros. Cafe Bar No. is open from 9.00 to 02.00.",
      ],
    ),
    Place(
      id: '40',
      asset: 'assets/png/places/image41.png',
      name: 'Vapriikki Museum and Exhibition Center',
      rating: '125 ratings',
      category: Category.walk,
      content: [
        "Housed in a renovated Tampella textile factory, this modern exhibition center regularly hosts a wide range of exhibitions. It is almost impossible to predict the theme of the next exhibition; it could be anything - from bicycles to Buddhism. There is also a permanent exhibition dedicated to the history of the city, as well as an excellent mineral museum, a natural history museum and a shoe museum (Tampere was famous for its shoe industry). There is even a museum of ice hockey, small in area, but with many interesting exhibits - the main sporting passion of Finland. Address: Museokeskus Vapriikki, Alaverstaanraitti, Tampere, Finland.",
      ],
    ),
    Place(
      id: '41',
      asset: 'assets/png/places/image42.png',
      name: 'Tampere Cathedral',
      rating: '8654 ratings',
      category: Category.walk,
      content: [
        "Tampere Cathedral, a typical example of national romantic architecture in the Art Nouveau style, was erected in 1907. The frescoes and stained glass windows were created for it by Hugo Simberg. Looking at his works, you realize all their ambiguity: a procession of apostles in the form of naked children carrying the “garland of life”, skeletons in dark robes tending plants in the “garden of Death”, a wounded angel carried on a stretcher by two children... The rather unusual altar will cause you no less confusion: there is a painting “The Resurrection” made in a similar style by Magnus Enckel, another Finnish symbolist artist. The snake depicted on the dome arch further enhances the feeling of strangeness and ambiguity that does not leave you from the very moment you cross the threshold of this cathedral. Address: Tampere Cathedral, Tuomiokirkonkatu, Tampere, Finland.",
      ],
    ),
    Place(
      id: '42',
      asset: 'assets/png/places/image43.png',
      name: 'Museum "Workers\' Quarter of Amuri"',
      rating: '512 ratings',
      category: Category.walk,
      content: [
        "Five one-story houses with 32 apartments, a bakery, a shoe workshop, a public sauna, two department stores and a cafe - all these wooden buildings are exhibits of the Amuri Workers' Quarter museum. The interiors of the 1880s-1970s have been recreated in residential and public buildings (this working-class quarter was built in 1882, resettled in 1973 and turned into an open-air museum). Explanatory signs describe the lives of the fictional residents of these apartments, and although these people are fictitious, their fates and stories are quite typical for these historical periods. Different times, different people, different destinies... It’s as if you are taking a trip into the past. A visit to this museum complex will be not only educational for you, but also interesting. Address: Amurin Museokortteli, Satakunnankatu, Tampere, Finland.",
      ],
    ),
    Place(
      id: '44',
      asset: 'assets/png/places/image45.png',
      name: 'Spy Museum',
      rating: '7436 ratings',
      category: Category.walk,
      content: [
        "The unusual spy museum, which is part of the Finlayson entertainment and exhibition center, will be appreciated by those who go on a trip with teenage children. Here you will learn the stories of famous Finnish and foreign spies, see a well-curated collection of all sorts of gadgets used by international spies of the Cold War era, as well as numerous gadgets from the arsenal of James Bond. For an additional fee, children aged 7 years and over can try to take the aptitude test for studying at the KGB cadet school. Those interested can take a lie detector test. Address: Spy Museum, Satakunnankatu, Tampere, Finland.",
      ],
    ),
    Place(
      id: '45',
      asset: 'assets/png/places/image46.png',
      name: 'Werstas Labor Museum',
      rating: '421 ratings',
      category: Category.walk,
      content: [
        "The Verstas Museum hosts frequently changing temporary exhibitions that highlight the region's various industries and the lives of Finnish workers during different historical periods. However, the museum also has three permanent exhibitions. The first places a deep emphasis on weaving and is, in fact, a textile museum. The second is a reconstruction of typical workplaces - a store and a printing house - during different periods of history. In the third room you will see a huge steam engine, which in the 19th century powered the machines at the Finlayson factory. Address: TYÖVÄENMUSEO WERSTAS, Väinö Linnan aukio, Tampere, Finland.",
      ],
    ),
    Place(
      id: '46',
      asset: 'assets/png/places/image47.png',
      name: 'Sarah Hilden Art Museum',
      rating: '4728 ratings',
      category: Category.walk,
      content: [
        "This museum, located in the Särkänniemi amusement park, features a collection of works by contemporary Finnish and international artists and sculptors collected by local businesswoman and art collector Sarah Hilden (1905-1993). Temporary exhibitions are periodically held here. The windows of the museum café offer beautiful views of the surrounding area. Address: Sara Hildénin taidemuseo, Laiturikatu, Tampere, Finland.",
      ],
    ),
    Place(
      id: '47',
      asset: 'assets/png/places/image48.png',
      name: 'Moomin Museum',
      rating: '167 ratings',
      category: Category.walk,
      isPremium: true,
      content: [
        "Experience the world of the incredibly popular Moomins at this impressive museum in Tampere Hall. Here you will see Tove Jansson's original drawings and stunning three-dimensional installations depicting scenes from whimsical stories. If you are traveling with children, then the Moomin Museum is a must-visit place in Tampere. Address: Muumimuseo, Yliopistonkatu, Tampere, Finland.",
      ],
    ),
    Place(
      id: '48',
      asset: 'assets/png/places/image49.png',
      name: 'Finlayson Center',
      rating: '156 ratings',
      category: Category.walk,
      isPremium: true,
      content: [
        "Tampere's industrial era began with Scotsman James Finlayson, who founded a textile factory in the city in the 1820s. Later, in 1882, the building of this factory became the first industrial building in the Scandinavian countries to feature electric lighting. Today, the building has been converted into a shopping center. In addition to cafes and shops, you will find a cinema, a beer bar and several interesting museums here. Address: Finlayson, Haarlankatu 4, 33210 Tampere, Finland.",
      ],
    ),
    Place(
      id: '49',
      asset: 'assets/png/places/image50.png',
      name: 'Nyasinneula observation tower',
      rating: '7423 ratings',
      category: Category.walk,
      isPremium: true,
      content: [
        "The 168 m high Näsinneula observation tower is located in the Särkänniemi amusement park. This is the tallest tower not only in Finland, but in all of Scandinavia, and this alone makes it worth a visit. And at an altitude of 120 m there is a restaurant located on a rotating platform. From there you can enjoy breathtaking panoramic views of the city and its surrounding lakes. Address: Näsinneula, Laiturikatu 1, 33230 Tampere, Finland.",
      ],
    ),
  ];
}
